//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Simulation
{
    public class Header : Message
    {
        public const string RosMessageName = "simulation_msgs/Header";

        public Time stamp;
        public int robot_id;

        public Header()
        {
            this.stamp = new Time();
            this.robot_id = 0;
        }

        public Header(Time stamp, int robot_id)
        {
            this.stamp = stamp;
            this.robot_id = robot_id;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(stamp.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.robot_id));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.stamp.Deserialize(data, offset);
            this.robot_id = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

    }
}
