//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.Simulation
{
    public class PoseRobot : Message
    {
        public const string RosMessageName = "simulation_msgs/PoseRobot";

        public int id;
        public Geometry.Pose pose;

        public PoseRobot()
        {
            this.id = 0;
            this.pose = new Geometry.Pose();
        }

        public PoseRobot(int id, Geometry.Pose pose)
        {
            this.id = id;
            this.pose = pose;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.id));
            listOfSerializations.AddRange(pose.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.id = BitConverter.ToInt32(data, offset);
            offset += 4;
            offset = this.pose.Deserialize(data, offset);

            return offset;
        }

    }
}
