//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Simulation
{
    public class PoseRobot : Message
    {
        public const string RosMessageName = "simulation_msgs/PoseRobot";

        public Header header;
        public Geometry.Pose pose;

        public PoseRobot()
        {
            this.header = new Header();
            this.pose = new Geometry.Pose();
        }

        public PoseRobot(Header header, Geometry.Pose pose)
        {
            this.header = header;
            this.pose = pose;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(pose.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.pose.Deserialize(data, offset);

            return offset;
        }

    }
}
