//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.Simulation
{
    public class RobotPoseArray : Message
    {
        public const string RosMessageName = "simulation_msgs/RobotPoseArray";

        public Std.Header header;
        public PoseRobot[] robots;

        public RobotPoseArray()
        {
            this.header = new Std.Header();
            this.robots = new PoseRobot[0];
        }

        public RobotPoseArray(Std.Header header, PoseRobot[] robots)
        {
            this.header = header;
            this.robots = robots;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            
            listOfSerializations.Add(BitConverter.GetBytes(robots.Length));
            foreach(var entry in robots)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            
            var robotsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.robots= new PoseRobot[robotsArrayLength];
            for(var i =0; i <robotsArrayLength; i++)
            {
                this.robots[i] = new PoseRobot();
                offset = this.robots[i].Deserialize(data, offset);
            }

            return offset;
        }

    }
}
