//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Simulation
{
    public class TwistRobot : Message
    {
        public const string RosMessageName = "simulation_msgs/TwistRobot";

        public Header header;
        public Geometry.Twist twist;

        public TwistRobot()
        {
            this.header = new Header();
            this.twist = new Geometry.Twist();
        }

        public TwistRobot(Header header, Geometry.Twist twist)
        {
            this.header = header;
            this.twist = twist;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.AddRange(twist.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            offset = this.twist.Deserialize(data, offset);

            return offset;
        }

    }
}
